// Code generated by scripts/generate-row-types.mjs. DO NOT EDIT.

export const EVENT_CATEGORIES = [
  "club",
  "academic",
  "social",
  "career",
  "sports",
  "arts",
  "community",
  "free_food",
] as const;
export type EventCategory = (typeof EVENT_CATEGORIES)[number];
export const EVENT_CONTENT_KINDS = [
  "student_event",
  "student_deadline",
  "student_application",
  "fundraiser",
  "other",
] as const;
export type EventContentKind = (typeof EVENT_CONTENT_KINDS)[number];
export const EVENT_SOURCES = [
  "instagram",
  "campus_website",
  "club_website",
  "manual",
] as const;
export type EventSource = (typeof EVENT_SOURCES)[number];

/** Generated from https://highlanderhub.local/schemas/events.upsert.schema.json — do not edit by hand. */
export interface EventRow {
  id: string;
  title: string;
  description: string;
  starts_at: string;
  all_day?: boolean | null;
  hosts?: { host: string; host_handle: string }[];
  ends_at?: string | null;
  location: string;
  host: string;
  host_handle?: string | null;
  category: "club" | "academic" | "social" | "career" | "sports" | "arts" | "community" | "free_food";
  content_kind: "student_event" | "student_deadline" | "student_application" | "fundraiser" | "other";
  tags: string[];
  source: "instagram" | "campus_website" | "club_website" | "manual";
  source_url?: string | null;
  image_url?: string | null;
  has_free_food: boolean;
  rsvp_required: boolean;
  rsvp_url?: string | null;
  scraped_at: string;
}
